ARG PHP_VERSION=8.1.9

FROM php:${PHP_VERSION}-fpm

ARG COMPOSER_VERSION=2.4.1

ENV COMPOSER_MEMORY_LIMIT=-1

RUN apt-get update && apt-get install -y \
     git zip bzip2 libpng-dev libpng-dev libicu-dev \
     vim libjpeg62-turbo-dev libfreetype6-dev libonig-dev \
     libpq-dev libxpm-dev libvpx-dev libbz2-dev zlib1g-dev libzip-dev gnumeric \
    && curl -sS https://getcomposer.org/installer | php -- --version="${COMPOSER_VERSION}" --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-install intl bcmath mbstring bz2 gd zip pgsql pdo_pgsql opcache pcntl

RUN docker-php-ext-enable intl pcntl

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN usermod -u 1000 www-data

COPY ./.docker/php/conf/horizon.conf /etc/supervisor/conf.d/horizon.conf
COPY ./.docker/php/conf/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www

EXPOSE 9000
CMD ["php-fpm"]
